"""Canonical ScheduleOccurrence.decision_reason values for runtime (#56).

Scheduler decision evidence is historical. Do NOT overwrite with Execution
terminal outcomes — Occurrence.status already projects the terminal state.
"""

from __future__ import annotations

# Timely / manual
DUE = "DUE"
MANUAL_TRIGGER = "MANUAL_TRIGGER"

# Misfire
MISFIRE_SKIP = "MISFIRE_SKIP"
MISFIRE_RUN_ONCE = "MISFIRE_RUN_ONCE"
MISFIRE_CATCH_UP = "MISFIRE_CATCH_UP"
MISFIRE_COALESCED = "MISFIRE_COALESCED"
MISFIRE_CATCH_UP_LIMIT = "MISFIRE_CATCH_UP_LIMIT"

# Overlap
OVERLAP_SKIP = "OVERLAP_SKIP"
OVERLAP_QUEUE = "OVERLAP_QUEUE"
OVERLAP_REPLACE = "OVERLAP_REPLACE"
OVERLAP_REPLACE_WAIT = "OVERLAP_REPLACE_WAIT"
REPLACE_SUPERSEDED = "REPLACE_SUPERSEDED"

# Fire-time / target failures (automatic due only)
TARGET_PRECONDITION_FAILED = "TARGET_PRECONDITION_FAILED"
AUTHORIZATION_REVOKED = "AUTHORIZATION_REVOKED"
AGENT_SCHEDULE_EXECUTION_UNSUPPORTED = "AGENT_SCHEDULE_EXECUTION_UNSUPPORTED"

# Backward-compatible aliases used by older call sites / tests mid-migration.
OVERLAP_QUEUE_WAIT = OVERLAP_QUEUE
MISFIRE_CATCH_UP_TRIMMED = MISFIRE_CATCH_UP_LIMIT
AGENT_VERSION_UNSUPPORTED = AGENT_SCHEDULE_EXECUTION_UNSUPPORTED
FIRE_PRECONDITION_FAILED = TARGET_PRECONDITION_FAILED
