"""Canonical ScheduleOccurrence.decision_reason values for runtime (#56)."""

from __future__ import annotations

MISFIRE_SKIP = "MISFIRE_SKIP"
MISFIRE_CATCH_UP_TRIMMED = "MISFIRE_CATCH_UP_TRIMMED"
OVERLAP_SKIP = "OVERLAP_SKIP"
OVERLAP_QUEUE_WAIT = "OVERLAP_QUEUE_WAIT"
OVERLAP_REPLACE_WAIT = "OVERLAP_REPLACE_WAIT"
OVERLAP_REPLACE = "OVERLAP_REPLACE"
AGENT_VERSION_UNSUPPORTED = "AGENT_VERSION_UNSUPPORTED"
FIRE_PRECONDITION_FAILED = "FIRE_PRECONDITION_FAILED"
MANUAL_TRIGGER = "MANUAL_TRIGGER"
EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
EXECUTION_FAILED = "EXECUTION_FAILED"
EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
EXECUTION_TIMED_OUT = "EXECUTION_TIMED_OUT"
