#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.server"
COMPOSE_FILES=(-f "$ROOT_DIR/compose.yaml" -f "$ROOT_DIR/compose.server.yaml")
SECRETS_DIR="$ROOT_DIR/infra/secrets/server"

usage() {
  cat <<'EOF'
Usage: ./scripts/deploy.sh [command]

Commands:
  deploy         Configure if needed, validate, migrate, deploy, and smoke-test (default)
  --reconfigure  Re-run interactive configuration, then deploy
  --status       Show container status
  --logs         Follow key service logs
  --restart      Restart runtime services
  --down         Stop MCPFlow containers without deleting volumes
  --help         Show this help
EOF
}

log() { printf '\n==> %s\n' "$*"; }
fail() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

compose() {
  docker compose --env-file "$ENV_FILE" "${COMPOSE_FILES[@]}" "$@"
}

read_default() {
  local prompt="$1" default="$2" value
  read -r -p "$prompt [$default]: " value
  printf '%s' "${value:-$default}"
}

write_env() {
  local host network entrypoint resolver environment log_level docs_enabled image_tag lease_seconds

  printf '\nMCPFlow server deployment configuration\n\n'
  while true; do
    read -r -p "Service domain (required, e.g. mcpflow.example.com): " host
    [[ -n "$host" ]] && break
    echo "Domain is required."
  done

  network="$(read_default "Traefik Docker network" "traefik")"
  entrypoint="$(read_default "Traefik HTTPS entrypoint" "websecure")"
  resolver="$(read_default "TLS certificate resolver" "letsencrypt")"
  environment="$(read_default "Deployment environment" "pilot")"
  log_level="$(read_default "Log level" "INFO")"
  docs_enabled="$(read_default "API docs enabled (true/false)" "false")"
  image_tag="$(read_default "Image tag" "$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo server)")"
  lease_seconds="$(read_default "Execution lease seconds" "60")"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy.sh. Do not commit.
MCPFLOW_HOST=$host
MCPFLOW_TRAEFIK_NETWORK=$network
MCPFLOW_TRAEFIK_ENTRYPOINT=$entrypoint
MCPFLOW_TRAEFIK_CERTRESOLVER=$resolver
MCPFLOW_ENVIRONMENT=$environment
MCPFLOW_DEBUG=false
MCPFLOW_LOG_LEVEL=$log_level
MCPFLOW_DOCS_ENABLED=$docs_enabled
MCPFLOW_IMAGE_TAG=$image_tag
MCPFLOW_EXECUTION_LEASE_SECONDS=$lease_seconds
MCPFLOW_OUTBOX_POLL_INTERVAL_SECONDS=1.0
MCPFLOW_OUTBOX_BATCH_SIZE=50
EOF
  chmod 600 "$ENV_FILE" || true
  echo "Saved: $ENV_FILE"
}

ensure_config() {
  if [[ ! -f "$ENV_FILE" ]]; then
    write_env
    return
  fi

  # shellcheck disable=SC1090
  source "$ENV_FILE"
  echo "Existing configuration found: $ENV_FILE"
  echo "  Domain          : ${MCPFLOW_HOST:-unset}"
  echo "  Traefik network : ${MCPFLOW_TRAEFIK_NETWORK:-unset}"
  echo "  Environment     : ${MCPFLOW_ENVIRONMENT:-unset}"
  echo "  Image tag       : ${MCPFLOW_IMAGE_TAG:-unset}"
  read -r -p "Use existing configuration? [Y/n]: " answer
  case "${answer:-Y}" in
    n|N|no|NO) write_env ;;
  esac
}

ensure_secrets() {
  mkdir -p "$SECRETS_DIR"
  if find "$SECRETS_DIR" -maxdepth 1 -type f 2>/dev/null | grep -q .; then
    log "Server secrets already exist; preserving them"
  else
    require_cmd python3
    log "Generating server secrets"
    python3 "$ROOT_DIR/infra/scripts/generate_local_secrets.py" --dir "$SECRETS_DIR"
  fi

  local required=(
    postgres_admin_password
    postgres_migration_password
    postgres_app_password
    minio_root_user
    minio_root_password
  )
  local item
  for item in "${required[@]}"; do
    [[ -s "$SECRETS_DIR/$item" ]] || fail "Missing server secret: $SECRETS_DIR/$item"
  done
}

preflight() {
  require_cmd docker
  docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
  [[ -f "$ROOT_DIR/compose.server.yaml" ]] || fail "compose.server.yaml not found"

  # shellcheck disable=SC1090
  source "$ENV_FILE"
  [[ -n "${MCPFLOW_HOST:-}" ]] || fail "MCPFLOW_HOST is not configured"
  [[ -n "${MCPFLOW_TRAEFIK_NETWORK:-}" ]] || fail "MCPFLOW_TRAEFIK_NETWORK is not configured"
  docker network inspect "$MCPFLOW_TRAEFIK_NETWORK" >/dev/null 2>&1 || \
    fail "External Traefik network '$MCPFLOW_TRAEFIK_NETWORK' does not exist"

  log "Validating Compose configuration"
  compose config >/dev/null
}

wait_services() {
  local label="$1"
  shift
  local deadline=$((SECONDS + 180))
  local svc cid status all_ready

  log "Waiting for $label"
  while (( SECONDS < deadline )); do
    all_ready=1
    for svc in "$@"; do
      cid="$(compose ps -q "$svc" 2>/dev/null || true)"
      if [[ -z "$cid" ]]; then
        all_ready=0
        continue
      fi
      status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$cid" 2>/dev/null || true)"
      case "$status" in
        healthy|running) ;;
        unhealthy|exited|dead)
          compose logs --tail=120 "$svc" || true
          fail "Service $svc entered state: $status"
          ;;
        *) all_ready=0 ;;
      esac
    done
    (( all_ready == 1 )) && return 0
    sleep 3
  done

  compose ps || true
  fail "$label did not become ready within 180 seconds"
}

wait_migration() {
  local deadline=$((SECONDS + 180))
  local cid state exit_code

  log "Waiting for Alembic migration"
  while (( SECONDS < deadline )); do
    cid="$(compose ps -a -q migration 2>/dev/null || true)"
    if [[ -n "$cid" ]]; then
      state="$(docker inspect -f '{{.State.Status}}' "$cid")"
      if [[ "$state" == "exited" ]]; then
        exit_code="$(docker inspect -f '{{.State.ExitCode}}' "$cid")"
        if [[ "$exit_code" == "0" ]]; then
          echo "Migration completed successfully"
          return 0
        fi
        compose logs --tail=200 migration || true
        fail "Migration failed with exit code $exit_code"
      fi
      [[ "$state" == "dead" ]] && fail "Migration container entered dead state"
    fi
    sleep 2
  done

  compose logs --tail=200 migration || true
  fail "Migration did not complete within 180 seconds"
}

smoke_test() {
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  if ! command -v curl >/dev/null 2>&1; then
    echo "curl not installed; skipping external HTTPS smoke test"
    return 0
  fi

  local url="https://${MCPFLOW_HOST}/health/ready"
  local i
  log "HTTPS smoke test: $url"
  for i in {1..30}; do
    if curl --fail --silent --show-error --max-time 5 "$url" >/dev/null; then
      echo "Health check passed"
      return 0
    fi
    sleep 2
  done
  fail "HTTPS readiness check failed: $url"
}

deploy_core() {
  ensure_secrets
  preflight

  log "Building application images"
  compose build api worker outbox migration frontend

  log "Starting stateful dependencies"
  compose up -d postgres redis object-storage
  wait_services "stateful dependencies" postgres redis object-storage

  log "Running Alembic migration (fail-fast)"
  compose up -d migration
  wait_migration

  log "Starting MCPFlow runtime"
  compose up -d api worker outbox frontend
  wait_services "runtime services" api worker outbox frontend postgres redis object-storage
  smoke_test

  log "Deployment complete"
  compose ps
}

deploy() {
  ensure_config
  deploy_core
}

status() {
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  compose ps -a
}

logs() {
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  compose logs -f --tail=200 api worker outbox migration postgres redis frontend
}

restart_runtime() {
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  preflight
  compose restart api worker outbox frontend
  wait_services "runtime services" api worker outbox frontend postgres redis object-storage
  smoke_test
}

down() {
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  echo "This stops containers but preserves PostgreSQL/Redis/Object Storage volumes."
  compose down
}

cd "$ROOT_DIR"
case "${1:-deploy}" in
  deploy) deploy ;;
  --reconfigure) write_env; deploy_core ;;
  --status) status ;;
  --logs) logs ;;
  --restart) restart_runtime ;;
  --down) down ;;
  --help|-h) usage ;;
  *) usage; fail "Unknown command: $1" ;;
esac
